// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY01MzyUu8g5T0pGdAEa8S54Hwn92FqeU',
    appId: '1:396590012961:web:4fbeb807f10020d02d6160',
    messagingSenderId: '396590012961',
    projectId: 'fluttermatching-b8667',
    authDomain: 'fluttermatching-b8667.firebaseapp.com',
    storageBucket: 'fluttermatching-b8667.appspot.com',
    measurementId: 'G-RWZL37NTJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCljf_eg3baLo_O2NjpyFHbXnSha3ZRphM',
    appId: '1:396590012961:android:54e0e7d0167ddecc2d6160',
    messagingSenderId: '396590012961',
    projectId: 'fluttermatching-b8667',
    storageBucket: 'fluttermatching-b8667.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtfKSFIRBiECYTRPYPwfTHwMkg96P8oAM',
    appId: '1:396590012961:ios:877be81999d9eb982d6160',
    messagingSenderId: '396590012961',
    projectId: 'fluttermatching-b8667',
    storageBucket: 'fluttermatching-b8667.appspot.com',
    iosClientId: '396590012961-5c19u9bm7eafhjmg5nnqbpep1u3t1qm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMatchingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtfKSFIRBiECYTRPYPwfTHwMkg96P8oAM',
    appId: '1:396590012961:ios:877be81999d9eb982d6160',
    messagingSenderId: '396590012961',
    projectId: 'fluttermatching-b8667',
    storageBucket: 'fluttermatching-b8667.appspot.com',
    iosClientId: '396590012961-5c19u9bm7eafhjmg5nnqbpep1u3t1qm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMatchingApp',
  );
}
